// supabase/functions/_shared/ai/types.ts

/** The canonical request object understood by every AI provider. */
export interface AIRequest {
  prompt: string;
  modelId?: string;
  temperature?: number;
  maxTokens?: number;
}

/** The AI service always returns the raw text generated by the provider. */
export type AIResponse = string;

/**
 * Contract that every AI provider must fulfil.
 * Providers receive an AIRequest and return a Promise<AIResponse>.
 * The service layer and registry communicate exclusively through this interface —
 * they never import concrete provider classes.
 */
export interface AIProvider {
  generate(request: AIRequest): Promise<AIResponse>;
}